clear folder if the -o folder if needed
Monitor221hz/Pandora-Behaviour-Engine-Plus pull request #309
Opened 2024-09-09 21:05 UTC by BryanAldrich

if -o is set, and that folder isn't the current folder, then clear it (minus a few specific files).

May want to double check  my logic. I believe it is right.

Also included is an additional load call to load from the .exe folder, the current/working folder and the output folder. The reason for this is so I get the templates from base Pandora, Nemsis configurations from other mods, but my ActiveMods.txt gets deployed to my custom output path.

Also, i noticed that FNIS.esp was completely deleted. I know nothing here requires it, but do other mods? or is that a huge question that would depend.

Thanks!

2024-09-09 21:57 UTC, Monitor221hz requested changes
Looks good, just one thing. can you change the type of the first parameter of the `LoadModFolder` function in `EngineViewModel` into a `Hashset<IModInfo>` and make the appropriate changes in the calling code? Would reduce the lookup time for duplicate mods as the amount of total mods increase in size.

2024-09-09 21:59 UTC, Monitor221hz commented
After the change is made I'll merge it soon. Before this, there are a couple of critical fixes that I need to merge and test. Thank you for your work.

2024-09-10 01:57 UTC, BryanAldrich commented
The HashSet change is easy enough, have to convert it a couple lines later, however, it will mean that if there are multiple versions of the same code, then each will show in the list. Do you want only the latest version showing?

2024-09-10 17:36 UTC, BryanAldrich commented
Well, that is exactly what it will do. I wish Vortex/MO2(?) had a proper way to let you delete files as they only let you override files. Probably should handle 0-byte/blank/invalid XML files somewhere (Precision Creatures current release has 2 busted XML files in it).

Added the copy for FNIS.esp to go with your other PR.

2024-10-18 12:44 UTC, merged

2024-10-18 13:26 UTC, Monitor221hz commented
So, I misunderstood what this code is meant to do. I assumed it was supposed to clear the output metadata ("ActiveMods.txt") files in a single run, but right now it's straight up deleting Nemesis_Engine and Pandora_Engine contents when the output argument is active, which makes the rest of the patching process throw an exception because the mod folders no longer exist. Then on the following runs, the engine does not read anything except the default mods because all the other mods have been deleted.

It also nuked my testing environment of over a hundred behavior patches when I ran it. But then again, it's partly my own fault for not looking at the code closely enough.

**If** this is intended behavior, please take some time to look through the output code to see what files are needed. The behavior mod folders should only be getting read, because the output hkx go into a different directory on export anyway.